### ISSUE TITLE
mod function truncates floating point data types to integer values

### ISSUE THREAD

**Issue by alexamici** [avalentino/gdal-pixfun-plugin#3]
The `mod` pixfun incorrectly truncates floats to integer values in most circumstances, depending on the platform and on something I could not pinpoint, as I get different results on two Ubuntu 14.04 systems. On one machine the `mod` pixfun works correctly and on the other it returns truncated data.

Furthermore, on Mac OS X I get the following compile-time warning:

```
$ make
[...]
cc -g -pedantic -fPIC -Wall -Wno-long-long -I/usr/local/Cellar/gdal/1.11.3_1/include    -c -o pixelfunctions.o pixelfunctions.c
pixelfunctions.c:728:35: warning: using integer absolute value function 'abs' when argument is of floating point type
      [-Wabsolute-value]
                dfPixVal = log10( abs( dfPixVal ) );
                                  ^
pixelfunctions.c:728:35: note: use function 'fabs' instead
                dfPixVal = log10( abs( dfPixVal ) );
                                  ^~~
                                  fabs
1 warning generated.
cc -shared -o gdal_PIXFUN.so pixfunplugin.o pixelfunctions.o -L/usr/local/Cellar/gdal/1.11.3_1/lib -lgdal
```

Looking at the code I see two `abs` calls (the one in the compile warning and another one inside ModulePixelFunc) that should be `fabs` calls for floating point data types.

I tried to change them to `fabs` unconditionally, which may well be wrong, and the test suite passes.

**Comment by avalentino** [comment]
Thanks @alexamici
